class CfgPatches {
    class alive_rhs_ru {
        units[] = {
            "O_aliverhsru_rifleman_01",
            "O_aliverhsru_Rifleman_AT_01",
            "O_aliverhsru_Automatic_Rifleman_01",
            "O_aliverhsru_Squad_Leader_01",
            "O_aliverhsru_Medic_01",
            "O_aliverhsru_AT_Special_01",
            "O_aliverhsru_AA_Special_01",
            "O_aliverhsru_shell_arty_static_01",
            "O_aliverhsru_mortar_01",
            "O_aliverhsru_GAZ_01",
            "O_aliverhsru_UAZ_01",
            "O_aliverhsru_Sniper_01",
            "O_aliverhsru_Spotter_01",
            "O_aliverhsru_Machine_Gunner_01",
            "O_aliverhsru_Gren_RPG_01",
            "O_aliverhsru_Gren_RPG_Assist_01",
            "O_aliverhsru_Marksman_01",
            "O_aliverhsru_Officer_01",
            "O_aliverhsru_Officer_Armored_01",
            "O_aliverhsru_Grenadier_01",
            "O_aliverhsru_GAZ_No_Hatch_01",
            "O_aliverhsru_BTR80_01",
            "O_aliverhsru_BTR80A_01",
            "O_aliverhsru_BTR70_01",
            "O_aliverhsru_BMP1_01",
            "O_aliverhsru_BMP2_01",
            "O_aliverhsru_BMP3_01",
            "O_aliverhsru_BMP3_Early_01",
            "O_aliverhsru_Efreitor_01",
            "O_aliverhsru_Sergeant_01",
            "O_aliverhsru_T72_01",
            "O_aliverhsru_T90_01",
            "O_aliverhsru_T80U_01",
            "O_aliverhsru_T80_01",
            "O_aliverhsru_Ural_01",
            "O_aliverhsru_Ural_Zu_23_01",
            "O_aliverhsru_Ural_Fuel_01",
            "O_aliverhsru_GAZ_02",
            "O_aliverhsru_GAZ_Truck_Open_01",
            "O_aliverhsru_BM21_01",
            "O_aliverhsru_Su_34_LGB_01",
            "O_aliverhsru_Su_34_AGM_01",
            "O_aliverhsru_Su_24_Frogfoot_01",
            "O_aliverhsru_MI_24P_FAB_01",
            "O_aliverhsru_MI_24P_CAS_01",
            "O_aliverhsru_MI_24V_CAS_01",
            "O_aliverhsru_MI_24V_FAB_01",
            "O_aliverhsru_MI_8_01",
            "O_aliverhsru_MI_8Rockets_01",
            "O_aliverhsru_Ka_52_01",
            "O_aliverhsru_Ka_60_01",
            "O_aliverhsru_NSV_01",
            "O_aliverhsru_KORD_01",
            "O_aliverhsru_SPG_01",
            "O_aliverhsru_AA_Turret_01",
            "O_aliverhsru_Tunguska_01",
            "O_aliverhsru_Mi_28_01"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
            "rhs_c_troops",
            "rhs_c_heavyweapons",
            "rhs_c_cars",
            "rhs_c_a2port_car",
            "CUP_Creatures_Military_Russia",
            "rhs_c_btr",
            "ace_compat_rhs_afrf3",
            "rhs_c_bmp",
            "rhs_c_bmp3",
            "rhs_c_t72",
            "rhs_c_tanks",
            "rhsgref_c_vehicles_ret",
            "rhs_c_trucks",
            "CUP_AirVehicles_SU34",
            "CUP_AirVehicles_Su25",
            "rhs_c_a2port_air",
            "rhs_c_a3retex",
            "CUP_TrackedVehicles_2S6M",
            "rhs_c_mi28"
        };
        author = "Ryan Parsons";
        authors[] = { "Ryan Parsons" };
    };
};
