//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 176.143187 on Stable branch
// Generated with ALiVE version 1.4.0.1709191
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class alive_MEM {
        displayName = "Alive Middle Eastern Militia";
        side = 0;
        flag = "CUP\BaseConfigs\CUP_BaseConfigs\Data\Flags\flag_tkm_co";
        icon = "CUP\BaseConfigs\CUP_BaseConfigs\Data\Flags\flag_tkm_co";
        priority = 0;
    };
};

class CfgGroups {
    class EAST {

        class alive_MEM {
            name = "Alive Middle Eastern Militia";

            class Infantry {
                name = "Infantry";

                class alivemem_infantry_squad {
                    name = "Squad";
                    side = 0;
                    faction = "alive_MEM";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_GP25_01";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_PKM_01";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_AKM_01";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_AKM_01";
                    };
                    class Unit4 {
                        position[] = { -10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_Lee_Enfield_01";
                    };
                    class Unit5 {
                        position[] = { 15 , -15 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_Lee_Enfield_01";
                    };
                };

                class alivemem_infantry_team {
                    name = "Team";
                    side = 0;
                    faction = "alive_MEM";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_GP25_01";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_AKM_01";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_PKM_01";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_Lee_Enfield_01";
                    };
                };

                class alivemem_infantry_squad_at {
                    name = "Squad (AT)";
                    side = 0;
                    faction = "alive_MEM";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_GP25_01";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_PKM_01";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_RPG_01";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_AKM_01";
                    };
                    class Unit4 {
                        position[] = { -10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_Lee_Enfield_01";
                    };
                    class Unit5 {
                        position[] = { 15 , -15 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_AKM_01";
                    };
                };

                class alivemem_infantry_team_at {
                    name = "Team (AT)";
                    side = 0;
                    faction = "alive_MEM";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_AKM_01";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_RPG_01";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_PKM_01";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_Lee_Enfield_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

                class alivemem_specops_scout_team {
                    name = "Scout Team";
                    side = 0;
                    faction = "alive_MEM";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_AKM_01";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_Sniper_01";
                    };
                };

            };

            class Motorized {
                name = "Motorized Infantry";

                class alivemem_motorized_squad_ural {
                    name = "Squad (Ural)";
                    side = 0;
                    faction = "alive_MEM";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_GP25_01";
                    };
                    class Unit1 {
                        position[] = { 6 , -13 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Ural_01";
                    };
                    class Unit2 {
                        position[] = { -6 , -13 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_AKM_01";
                    };
                    class Unit3 {
                        position[] = { 11 , -18 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_PKM_01";
                    };
                    class Unit4 {
                        position[] = { -11 , -18 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_AKM_01";
                    };
                    class Unit5 {
                        position[] = { 16 , -23 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_Lee_Enfield_01";
                    };
                    class Unit6 {
                        position[] = { -16 , -23 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_Lee_Enfield_01";
                    };
                };

                class alivemem_motorized_squad_at_ural {
                    name = "Squad (AT) (Ural)";
                    side = 0;
                    faction = "alive_MEM";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_GP25_01";
                    };
                    class Unit1 {
                        position[] = { 6 , -13 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Ural_01";
                    };
                    class Unit2 {
                        position[] = { -6 , -13 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_PKM_01";
                    };
                    class Unit3 {
                        position[] = { 11 , -18 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_RPG_01";
                    };
                    class Unit4 {
                        position[] = { -11 , -18 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_AKM_01";
                    };
                    class Unit5 {
                        position[] = { 16 , -23 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_Lee_Enfield_01";
                    };
                    class Unit6 {
                        position[] = { -16 , -23 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_Lee_Enfield_01";
                    };
                };

                class alivemem_motorized_team_uaz {
                    name = "Team (UAZ)";
                    side = 0;
                    faction = "alive_MEM";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_GP25_01";
                    };
                    class Unit1 {
                        position[] = { 5 , -7 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_UAZ_01";
                    };
                    class Unit2 {
                        position[] = { -5 , -7 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_PKM_01";
                    };
                    class Unit3 {
                        position[] = { -10 , -12 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_Lee_Enfield_01";
                    };
                };

                class alivemem_motorized_team_at_uaz {
                    name = "Team (AT) (UAZ)";
                    side = 0;
                    faction = "alive_MEM";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_GP25_01";
                    };
                    class Unit1 {
                        position[] = { 5 , -7 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_UAZ_01";
                    };
                    class Unit2 {
                        position[] = { -5 , -7 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_PKM_01";
                    };
                    class Unit3 {
                        position[] = { 10 , -12 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_RPG_01";
                    };
                };

                class alivemem_motorized_team_land_rover {
                    name = "Team (Land Rover)";
                    side = 0;
                    faction = "alive_MEM";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_GP25_01";
                    };
                    class Unit1 {
                        position[] = { 5 , -9 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Land_Rover_01";
                    };
                    class Unit2 {
                        position[] = { -5 , -9 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_PKM_01";
                    };
                    class Unit3 {
                        position[] = { -10 , -14 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_Lee_Enfield_01";
                    };
                };

                class alivemem_motorized_team_at_land_rover {
                    name = "Team (AT) (Land Rover)";
                    side = 0;
                    faction = "alive_MEM";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_GP25_01";
                    };
                    class Unit1 {
                        position[] = { 5 , -9 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Land_Rover_01";
                    };
                    class Unit2 {
                        position[] = { -5 , -9 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_RPG_01";
                    };
                    class Unit3 {
                        position[] = { 10 , -14 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_PKM_01";
                    };
                };

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

                class alivemem_mechanized_squad_btr_70 {
                    name = "Squad (BTR-70)";
                    side = 0;
                    faction = "alive_MEM";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_GP25_01";
                    };
                    class Unit1 {
                        position[] = { 7 , -15 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_BTR_70_01";
                    };
                    class Unit2 {
                        position[] = { -7 , -15 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_PKM_01";
                    };
                    class Unit3 {
                        position[] = { 12 , -20 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_AKM_01";
                    };
                    class Unit4 {
                        position[] = { -12 , -20 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_AKM_01";
                    };
                    class Unit5 {
                        position[] = { 17 , -25 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_Lee_Enfield_01";
                    };
                    class Unit6 {
                        position[] = { -17 , -25 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_aliveMEM_Guerilla_RPG_01";
                    };
                };

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class LOP_AM_OPF_Infantry_Rifleman;
    class LOP_AM_OPF_Infantry_Rifleman_OCimport_01 : LOP_AM_OPF_Infantry_Rifleman { scope = 0; class EventHandlers; };
    class LOP_AM_OPF_Infantry_Rifleman_OCimport_02 : LOP_AM_OPF_Infantry_Rifleman_OCimport_01 { class EventHandlers; };

    class LOP_AM_OPF_Infantry_Rifleman_3;
    class LOP_AM_OPF_Infantry_Rifleman_3_OCimport_01 : LOP_AM_OPF_Infantry_Rifleman_3 { scope = 0; class EventHandlers; };
    class LOP_AM_OPF_Infantry_Rifleman_3_OCimport_02 : LOP_AM_OPF_Infantry_Rifleman_3_OCimport_01 { class EventHandlers; };

    class LOP_AM_OPF_Infantry_GL;
    class LOP_AM_OPF_Infantry_GL_OCimport_01 : LOP_AM_OPF_Infantry_GL { scope = 0; class EventHandlers; };
    class LOP_AM_OPF_Infantry_GL_OCimport_02 : LOP_AM_OPF_Infantry_GL_OCimport_01 { class EventHandlers; };

    class LOP_AM_OPF_Infantry_AT;
    class LOP_AM_OPF_Infantry_AT_OCimport_01 : LOP_AM_OPF_Infantry_AT { scope = 0; class EventHandlers; };
    class LOP_AM_OPF_Infantry_AT_OCimport_02 : LOP_AM_OPF_Infantry_AT_OCimport_01 { class EventHandlers; };

    class LOP_AM_OPF_Infantry_Marksman;
    class LOP_AM_OPF_Infantry_Marksman_OCimport_01 : LOP_AM_OPF_Infantry_Marksman { scope = 0; class EventHandlers; };
    class LOP_AM_OPF_Infantry_Marksman_OCimport_02 : LOP_AM_OPF_Infantry_Marksman_OCimport_01 { class EventHandlers; };

    class LOP_AM_OPF_Infantry_AR;
    class LOP_AM_OPF_Infantry_AR_OCimport_01 : LOP_AM_OPF_Infantry_AR { scope = 0; class EventHandlers; };
    class LOP_AM_OPF_Infantry_AR_OCimport_02 : LOP_AM_OPF_Infantry_AR_OCimport_01 { class EventHandlers; };

    class LOP_AM_OPF_Infantry_Rifleman_2;
    class LOP_AM_OPF_Infantry_Rifleman_2_OCimport_01 : LOP_AM_OPF_Infantry_Rifleman_2 { scope = 0; class EventHandlers; };
    class LOP_AM_OPF_Infantry_Rifleman_2_OCimport_02 : LOP_AM_OPF_Infantry_Rifleman_2_OCimport_01 { class EventHandlers; };

    class LOP_AM_OPF_Infantry_Rifleman_4;
    class LOP_AM_OPF_Infantry_Rifleman_4_OCimport_01 : LOP_AM_OPF_Infantry_Rifleman_4 { scope = 0; class EventHandlers; };
    class LOP_AM_OPF_Infantry_Rifleman_4_OCimport_02 : LOP_AM_OPF_Infantry_Rifleman_4_OCimport_01 { class EventHandlers; };

    class LOP_AM_OPF_Infantry_Rifleman_5;
    class LOP_AM_OPF_Infantry_Rifleman_5_OCimport_01 : LOP_AM_OPF_Infantry_Rifleman_5 { scope = 0; class EventHandlers; };
    class LOP_AM_OPF_Infantry_Rifleman_5_OCimport_02 : LOP_AM_OPF_Infantry_Rifleman_5_OCimport_01 { class EventHandlers; };

    class LOP_AM_OPF_Landrover;
    class LOP_AM_OPF_Landrover_OCimport_01 : LOP_AM_OPF_Landrover { scope = 0; class EventHandlers; };
    class LOP_AM_OPF_Landrover_OCimport_02 : LOP_AM_OPF_Landrover_OCimport_01 { scope = 0; class EventHandlers; };

    class LOP_AM_OPF_Landrover_M2;
    class LOP_AM_OPF_Landrover_M2_OCimport_01 : LOP_AM_OPF_Landrover_M2 { scope = 0; class EventHandlers; class Turrets; };
    class LOP_AM_OPF_Landrover_M2_OCimport_02 : LOP_AM_OPF_Landrover_M2_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class LOP_AM_OPF_UAZ;
    class LOP_AM_OPF_UAZ_OCimport_01 : LOP_AM_OPF_UAZ { scope = 0; class EventHandlers; };
    class LOP_AM_OPF_UAZ_OCimport_02 : LOP_AM_OPF_UAZ_OCimport_01 { scope = 0; class EventHandlers; };

    class LOP_AM_OPF_UAZ_DshKM;
    class LOP_AM_OPF_UAZ_DshKM_OCimport_01 : LOP_AM_OPF_UAZ_DshKM { scope = 0; class EventHandlers; class Turrets; };
    class LOP_AM_OPF_UAZ_DshKM_OCimport_02 : LOP_AM_OPF_UAZ_DshKM_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CargoTurret_01;
        };
    };

    class LOP_AM_OPF_UAZ_AGS;
    class LOP_AM_OPF_UAZ_AGS_OCimport_01 : LOP_AM_OPF_UAZ_AGS { scope = 0; class EventHandlers; class Turrets; };
    class LOP_AM_OPF_UAZ_AGS_OCimport_02 : LOP_AM_OPF_UAZ_AGS_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CargoTurret_01;
        };
    };

    class LOP_AM_OPF_UAZ_SPG;
    class LOP_AM_OPF_UAZ_SPG_OCimport_01 : LOP_AM_OPF_UAZ_SPG { scope = 0; class EventHandlers; class Turrets; };
    class LOP_AM_OPF_UAZ_SPG_OCimport_02 : LOP_AM_OPF_UAZ_SPG_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CargoTurret_01;
        };
    };

    class LOP_AM_OPF_Offroad;
    class LOP_AM_OPF_Offroad_OCimport_01 : LOP_AM_OPF_Offroad { scope = 0; class EventHandlers; class Turrets; };
    class LOP_AM_OPF_Offroad_OCimport_02 : LOP_AM_OPF_Offroad_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
        };
    };

    class LOP_AM_OPF_Offroad_M2;
    class LOP_AM_OPF_Offroad_M2_OCimport_01 : LOP_AM_OPF_Offroad_M2 { scope = 0; class EventHandlers; class Turrets; };
    class LOP_AM_OPF_Offroad_M2_OCimport_02 : LOP_AM_OPF_Offroad_M2_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class M2_Turret;
        };
    };

    class LOP_TKA_Ural;
    class LOP_TKA_Ural_OCimport_01 : LOP_TKA_Ural { scope = 0; class EventHandlers; class Turrets; };
    class LOP_TKA_Ural_OCimport_02 : LOP_TKA_Ural_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class LOP_TKA_Ural_open;
    class LOP_TKA_Ural_open_OCimport_01 : LOP_TKA_Ural_open { scope = 0; class EventHandlers; class Turrets; };
    class LOP_TKA_Ural_open_OCimport_02 : LOP_TKA_Ural_open_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class rhs_btr70_msv;
    class rhs_btr70_msv_OCimport_01 : rhs_btr70_msv { scope = 0; class EventHandlers; class Turrets; };
    class rhs_btr70_msv_OCimport_02 : rhs_btr70_msv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CommanderOptics;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
            class CargoTurret_07;
            class CargoTurret_08;
            class Commander_Out;
        };
    };

    class rhs_btr60_msv;
    class rhs_btr60_msv_OCimport_01 : rhs_btr60_msv { scope = 0; class EventHandlers; class Turrets; };
    class rhs_btr60_msv_OCimport_02 : rhs_btr60_msv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CommanderOptics;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
            class CargoTurret_07;
            class CargoTurret_08;
            class Commander_Out;
        };
    };

    class rhsgref_BRDM2_msv;
    class rhsgref_BRDM2_msv_OCimport_01 : rhsgref_BRDM2_msv { scope = 0; class EventHandlers; class Turrets; };
    class rhsgref_BRDM2_msv_OCimport_02 : rhsgref_BRDM2_msv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CommanderOptics;
            class MainTurret;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
        };
    };

    class LOP_AM_OPF_Static_SPG9;
    class LOP_AM_OPF_Static_SPG9_OCimport_01 : LOP_AM_OPF_Static_SPG9 { scope = 0; class EventHandlers; class Turrets; };
    class LOP_AM_OPF_Static_SPG9_OCimport_02 : LOP_AM_OPF_Static_SPG9_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class LOP_AM_OPF_NSV_TriPod;
    class LOP_AM_OPF_NSV_TriPod_OCimport_01 : LOP_AM_OPF_NSV_TriPod { scope = 0; class EventHandlers; class Turrets; };
    class LOP_AM_OPF_NSV_TriPod_OCimport_02 : LOP_AM_OPF_NSV_TriPod_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class LOP_AM_OPF_Kord;
    class LOP_AM_OPF_Kord_OCimport_01 : LOP_AM_OPF_Kord { scope = 0; class EventHandlers; class Turrets; };
    class LOP_AM_OPF_Kord_OCimport_02 : LOP_AM_OPF_Kord_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class LOP_AM_OPF_Kord_High;
    class LOP_AM_OPF_Kord_High_OCimport_01 : LOP_AM_OPF_Kord_High { scope = 0; class EventHandlers; class Turrets; };
    class LOP_AM_OPF_Kord_High_OCimport_02 : LOP_AM_OPF_Kord_High_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class LOP_AM_OPF_Static_DSHKM;
    class LOP_AM_OPF_Static_DSHKM_OCimport_01 : LOP_AM_OPF_Static_DSHKM { scope = 0; class EventHandlers; class Turrets; };
    class LOP_AM_OPF_Static_DSHKM_OCimport_02 : LOP_AM_OPF_Static_DSHKM_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };


    class O_aliveMEM_Guerilla_AKM_01 : LOP_AM_OPF_Infantry_Rifleman_OCimport_02 {
        author = "Ryan Parsons";
        scope = 2;
        scopeCurator = 2;
        displayName = "Guerilla AKM";
        side = 0;
        faction = "alive_MEM";

        identityTypes[] = { "Head_TK" , "LanguagePER_F" , "G_IRAN_default" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};_this setunitloadout [['rhs_weap_akm','rhs_acc_dtkakm','','',['rhs_30Rnd_762x39mm',30],[],''],[],[],['LOP_U_AM_Fatigue_03_4',[['FirstAidKit',1],['rhs_30Rnd_762x39mm',4,30],['rhs_mag_rdg2_white',1,1],['rhs_mag_rgd5',1,1]]],[],[],'LOP_H_Turban_mask','',[],['ItemMap','','','ItemCompass','','']];reload _this};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_aliveMEM_Guerilla_Lee_Enfield_01 : LOP_AM_OPF_Infantry_Rifleman_3_OCimport_02 {
        author = "Ryan Parsons";
        scope = 2;
        scopeCurator = 2;
        displayName = "Guerilla Lee Enfield";
        side = 0;
        faction = "alive_MEM";

        identityTypes[] = { "Head_TK" , "LanguagePER_F" , "G_IRAN_default" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};_this setunitloadout [['LOP_Weap_LeeEnfield','','','',['LOP_10rnd_77mm_mag',10],[],''],[],[],['LOP_U_AM_Fatigue_02_4',[['FirstAidKit',1],['LOP_10rnd_77mm_mag',4,10],['rhs_mag_rdg2_white',1,1],['rhs_mag_rgd5',1,1]]],[],[],'LOP_H_Shemag_GRE','',[],['ItemMap','','','ItemCompass','','']];reload _this};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_aliveMEM_Guerilla_GP25_01 : LOP_AM_OPF_Infantry_GL_OCimport_02 {
        author = "Ryan Parsons";
        scope = 2;
        scopeCurator = 2;
        displayName = "Guerilla GP25";
        side = 0;
        faction = "alive_MEM";

        identityTypes[] = { "Head_TK" , "LanguagePER_F" , "G_IRAN_default" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};_this setunitloadout [['rhs_weap_akm_gp25','rhs_acc_dtkakm','','',['rhs_30Rnd_762x39mm',30],['rhs_VOG25',1],''],[],[],['LOP_U_AM_Fatigue_02_5',[['FirstAidKit',1],['rhs_30Rnd_762x39mm',4,30],['rhs_VOG25',4,1],['rhs_mag_rgd5',1,1]]],[],[],'LOP_H_Shemag_GRE','',[],['ItemMap','','','ItemCompass','','']];reload _this};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_aliveMEM_Guerilla_RPG_01 : LOP_AM_OPF_Infantry_AT_OCimport_02 {
        author = "Ryan Parsons";
        scope = 2;
        scopeCurator = 2;
        displayName = "Guerilla RPG";
        side = 0;
        faction = "alive_MEM";

        identityTypes[] = { "Head_TK" , "LanguagePER_F" , "G_IRAN_default" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};_this setunitloadout [['rhs_weap_aks74u','rhs_acc_pgs64_74u','','',['rhs_30Rnd_545x39_AK',30],[],''],['rhs_weap_rpg7','','','',[],[],''],[],['LOP_U_AM_Fatigue_01_4',[['FirstAidKit',1],['rhs_30Rnd_545x39_AK',3,30],['rhs_mag_rdg2_white',1,1],['rhs_mag_rgd5',1,1]]],[],['LOP_AM_RPG_Pack',[['rhs_rpg7_PG7VR_mag',1,1],['rhs_rpg7_PG7VL_mag',1,1]]],'LOP_H_Shemag_GRE','',[],['ItemMap','','','ItemCompass','','']];reload _this};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_aliveMEM_Guerilla_Sniper_01 : LOP_AM_OPF_Infantry_Marksman_OCimport_02 {
        author = "Ryan Parsons";
        scope = 2;
        scopeCurator = 2;
        displayName = "Guerilla Sniper";
        side = 0;
        faction = "alive_MEM";

        identityTypes[] = { "Head_TK" , "LanguagePER_F" , "G_IRAN_default" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};_this setunitloadout [['LOP_Weap_SVDS','','','rhs_acc_pso1m2',['rhs_10Rnd_762x54mmR_7N1',10],[],''],[],[],['LOP_U_AM_Fatigue_01_4',[['FirstAidKit',1],['rhs_10Rnd_762x54mmR_7N1',6,10],['rhs_mag_rdg2_white',1,1],['rhs_mag_rdg2_black',1,1],['rhs_mag_rgd5',2,1]]],[],[],'LOP_H_Turban','',[],['ItemMap','','','ItemCompass','','']];reload _this};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_aliveMEM_Guerilla_PKM_01 : LOP_AM_OPF_Infantry_AR_OCimport_02 {
        author = "Ryan Parsons";
        scope = 2;
        scopeCurator = 2;
        displayName = "Guerilla PKM";
        side = 0;
        faction = "alive_MEM";

        identityTypes[] = { "Head_TK" , "LanguagePER_F" , "G_IRAN_default" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};_this setunitloadout [['rhs_weap_pkm','','','',['rhs_100Rnd_762x54mmR',100],[],''],[],[],['LOP_U_AM_Fatigue_01_5',[['FirstAidKit',1],['rhs_mag_rdg2_white',1,1],['rhs_mag_rdg2_black',1,1],['rhs_mag_rgd5',2,1]]],[],['LOP_AM_Fieldpack_PKM',[['rhs_100Rnd_762x54mmR',6,100]]],'LOP_H_Turban','',[],['ItemMap','','','ItemCompass','','']];reload _this};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_aliveMEM_Guerilla_AKMS_01 : LOP_AM_OPF_Infantry_Rifleman_2_OCimport_02 {
        author = "Ryan Parsons";
        scope = 2;
        scopeCurator = 2;
        displayName = "Guerilla AKMS";
        side = 0;
        faction = "alive_MEM";

        identityTypes[] = { "Head_TK" , "LanguagePER_F" , "G_IRAN_default" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};_this setunitloadout [['rhs_weap_akms','rhs_acc_dtkakm','','',['rhs_30Rnd_762x39mm',30],[],''],[],[],['LOP_U_AM_Fatigue_01_5',[['FirstAidKit',1],['rhs_30Rnd_762x39mm',5,30],['rhs_mag_rdg2_white',1,1],['rhs_mag_rdg2_black',1,1],['rhs_mag_rgd5',2,1]]],[],[],'LOP_H_Turban','',[],['ItemMap','','','ItemCompass','','']];reload _this};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_aliveMEM_Guerilla_AKS_74_01 : LOP_AM_OPF_Infantry_Rifleman_4_OCimport_02 {
        author = "Ryan Parsons";
        scope = 2;
        scopeCurator = 2;
        displayName = "Guerilla AKS-74";
        side = 0;
        faction = "alive_MEM";

        identityTypes[] = { "Head_TK" , "LanguagePER_F" , "G_IRAN_default" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};_this setunitloadout [['rhs_weap_aks74','rhs_acc_dtk1983','','',['rhs_30Rnd_545x39_AK',30],[],''],[],[],['LOP_U_AM_Fatigue_01_4',[['FirstAidKit',1],['rhs_30Rnd_545x39_AK',3,30],['rhs_mag_rdg2_white',1,1],['rhs_mag_rgn',1,1]]],[],[],'LOP_H_Pakol','',[],['ItemMap','','','ItemCompass','','']];reload _this};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_aliveMEM_Guerilla_AKS_74U_01 : LOP_AM_OPF_Infantry_Rifleman_5_OCimport_02 {
        author = "Ryan Parsons";
        scope = 2;
        scopeCurator = 2;
        displayName = "Guerilla AKS-74U";
        side = 0;
        faction = "alive_MEM";

        identityTypes[] = { "Head_TK" , "LanguagePER_F" , "G_IRAN_default" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};_this setunitloadout [['rhs_weap_aks74u','rhs_acc_pgs64_74u','','',['rhs_30Rnd_545x39_AK',30],[],''],[],[],['LOP_U_AM_Fatigue_01_4',[['FirstAidKit',1],['rhs_30Rnd_545x39_AK',3,30],['rhs_mag_rdg2_white',1,1],['rhs_mag_rgn',1,1]]],[],[],'LOP_H_Shemag_RED1','',[],['ItemMap','','','ItemCompass','','']];reload _this};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_aliveMEM_Land_Rover_01 : LOP_AM_OPF_Landrover_OCimport_02 {
        author = "Ryan Parsons";
        scope = 2;
        scopeCurator = 2;
        displayName = "Land Rover";
        side = 0;
        faction = "alive_MEM";
        crew = "O_aliveMEM_Guerilla_AKM_01";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_aliveMEM_Land_Rover_M2_01 : LOP_AM_OPF_Landrover_M2_OCimport_02 {
        author = "Ryan Parsons";
        scope = 2;
        scopeCurator = 2;
        displayName = "Land Rover M2";
        side = 0;
        faction = "alive_MEM";
        crew = "O_aliveMEM_Guerilla_AKM_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_aliveMEM_Guerilla_AKM_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_aliveMEM_UAZ_01 : LOP_AM_OPF_UAZ_OCimport_02 {
        author = "Ryan Parsons";
        scope = 2;
        scopeCurator = 2;
        displayName = "UAZ";
        side = 0;
        faction = "alive_MEM";
        crew = "O_aliveMEM_Guerilla_AKM_01";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_a2port_car\uaz\data\uaz_main_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Camo";

    };

    class O_aliveMEM_UAZ_Dshkm_01 : LOP_AM_OPF_UAZ_DshKM_OCimport_02 {
        author = "Ryan Parsons";
        scope = 2;
        scopeCurator = 2;
        displayName = "UAZ Dshkm";
        side = 0;
        faction = "alive_MEM";
        crew = "O_aliveMEM_Guerilla_AKM_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_aliveMEM_Guerilla_AKM_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_a2port_car\uaz\data\uaz_main_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_a2port_car\uaz\data\uaz_mount_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Camo";

    };

    class O_aliveMEM_UAZ_AGS_30_01 : LOP_AM_OPF_UAZ_AGS_OCimport_02 {
        author = "Ryan Parsons";
        scope = 2;
        scopeCurator = 2;
        displayName = "UAZ AGS-30";
        side = 0;
        faction = "alive_MEM";
        crew = "O_aliveMEM_Guerilla_AKM_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_aliveMEM_Guerilla_AKM_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_a2port_car\uaz\data\uaz_main_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_a2port_car\uaz\data\uaz_mount_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Camo";

    };

    class O_aliveMEM_UAZ_SPG_01 : LOP_AM_OPF_UAZ_SPG_OCimport_02 {
        author = "Ryan Parsons";
        scope = 2;
        scopeCurator = 2;
        displayName = "UAZ SPG";
        side = 0;
        faction = "alive_MEM";
        crew = "O_aliveMEM_Guerilla_AKM_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_aliveMEM_Guerilla_AKM_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_a2port_car\uaz\data\uaz_main_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_a2port_car\uaz\data\uaz_mount_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Camo";

    };

    class O_aliveMEM_Offroad_01 : LOP_AM_OPF_Offroad_OCimport_02 {
        author = "Ryan Parsons";
        scope = 2;
        scopeCurator = 2;
        displayName = "Offroad";
        side = 0;
        faction = "alive_MEM";
        crew = "O_aliveMEM_Guerilla_AKM_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\a3\Soft_F\Offroad_01\data\Offroad_01_ext_BASE01_CO.paa'];_unit setObjectTextureGlobal [1,'\a3\Soft_F\Offroad_01\data\Offroad_01_ext_BASE01_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "LOP_beige";

    };

    class O_aliveMEM_Offroad_M2_01 : LOP_AM_OPF_Offroad_M2_OCimport_02 {
        author = "Ryan Parsons";
        scope = 2;
        scopeCurator = 2;
        displayName = "Offroad M2";
        side = 0;
        faction = "alive_MEM";
        crew = "O_aliveMEM_Guerilla_AKM_01";

        class Turrets : Turrets {
            class M2_Turret : M2_Turret { gunnerType = "O_aliveMEM_Guerilla_AKM_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\a3\Soft_F\Offroad_01\data\Offroad_01_ext_BASE01_CO.paa'];_unit setObjectTextureGlobal [1,'\a3\Soft_F\Offroad_01\data\Offroad_01_ext_BASE01_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "LOP_beige";

    };

    class O_aliveMEM_Ural_01 : LOP_TKA_Ural_OCimport_02 {
        author = "Ryan Parsons";
        scope = 2;
        scopeCurator = 2;
        displayName = "Ural";
        side = 0;
        faction = "alive_MEM";
        crew = "O_aliveMEM_Guerilla_AKM_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_a2port_car\ural\data\ural_kabina_rus_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_a2port_car\ural\data\ural_plachta_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Camo";

    };

    class O_aliveMEM_Ural_Open_01 : LOP_TKA_Ural_open_OCimport_02 {
        author = "Ryan Parsons";
        scope = 2;
        scopeCurator = 2;
        displayName = "Ural (Open)";
        side = 0;
        faction = "alive_MEM";
        crew = "O_aliveMEM_Guerilla_AKM_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_a2port_car\ural\data\ural_kabina_rus_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_a2port_car\ural\data\ural_plachta_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Camo";

    };

    class O_aliveMEM_BTR_70_01 : rhs_btr70_msv_OCimport_02 {
        author = "Ryan Parsons";
        scope = 2;
        scopeCurator = 2;
        displayName = "BTR-70";
        side = 0;
        faction = "alive_MEM";
        crew = "O_aliveMEM_Guerilla_AKM_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_aliveMEM_Guerilla_AKM_01"; };
            class CommanderOptics : CommanderOptics { gunnerType = "O_aliveMEM_Guerilla_AKM_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
            class CargoTurret_07 : CargoTurret_07 { gunnerType = ""; };
            class CargoTurret_08 : CargoTurret_08 { gunnerType = ""; };
            class Commander_Out : Commander_Out { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsgref\addons\rhsgref_vehicles_ret\data\misc\btr70_tak_1_co.paa'];_unit setObjectTextureGlobal [1,'rhsgref\addons\rhsgref_vehicles_ret\data\misc\btr70_tak_2_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Takistan";

    };

    class O_aliveMEM_BTR_60PB_01 : rhs_btr60_msv_OCimport_02 {
        author = "Ryan Parsons";
        scope = 2;
        scopeCurator = 2;
        displayName = "BTR-60PB";
        side = 0;
        faction = "alive_MEM";
        crew = "O_aliveMEM_Guerilla_AKM_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_aliveMEM_Guerilla_AKM_01"; };
            class CommanderOptics : CommanderOptics { gunnerType = "O_aliveMEM_Guerilla_AKM_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
            class CargoTurret_07 : CargoTurret_07 { gunnerType = ""; };
            class CargoTurret_08 : CargoTurret_08 { gunnerType = ""; };
            class Commander_Out : Commander_Out { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_a2port_armor_camo\data\btr60_body_3tone_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_a2port_armor_camo\data\btr60_details_3tone_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "3tone";

    };

    class O_aliveMEM_BRDM_2_01 : rhsgref_BRDM2_msv_OCimport_02 {
        author = "Ryan Parsons";
        scope = 2;
        scopeCurator = 2;
        displayName = "BRDM-2";
        side = 0;
        faction = "alive_MEM";
        crew = "O_aliveMEM_Guerilla_AKM_01";

        class Turrets : Turrets {
            class CommanderOptics : CommanderOptics { gunnerType = "O_aliveMEM_Guerilla_AKM_01"; };
            class MainTurret : MainTurret { gunnerType = "O_aliveMEM_Guerilla_AKM_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\rhsgref\addons\rhsgref_a2port_armor\brdm2\data\BRDM2_01_TKA_CO.paa'];_unit setObjectTextureGlobal [1,'\rhsgref\addons\rhsgref_a2port_armor\brdm2\data\brdm2_02_camo_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "takistan";

    };

    class O_aliveMEM_SPG_9_01 : LOP_AM_OPF_Static_SPG9_OCimport_02 {
        author = "Ryan Parsons";
        scope = 2;
        scopeCurator = 2;
        displayName = "SPG-9";
        side = 0;
        faction = "alive_MEM";
        crew = "LOP_AM_OPF_Infantry_Rifleman";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_aliveMEM_NSV_01 : LOP_AM_OPF_NSV_TriPod_OCimport_02 {
        author = "Ryan Parsons";
        scope = 2;
        scopeCurator = 2;
        displayName = "NSV";
        side = 0;
        faction = "alive_MEM";
        crew = "LOP_AM_OPF_Infantry_Rifleman";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_aliveMEM_KORD_01 : LOP_AM_OPF_Kord_OCimport_02 {
        author = "Ryan Parsons";
        scope = 2;
        scopeCurator = 2;
        displayName = "KORD (6T7)";
        side = 0;
        faction = "alive_MEM";
        crew = "LOP_AM_OPF_Infantry_Rifleman";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_aliveMEM_KORD_6U16_01 : LOP_AM_OPF_Kord_High_OCimport_02 {
        author = "Ryan Parsons";
        scope = 2;
        scopeCurator = 2;
        displayName = "KORD (6U16)";
        side = 0;
        faction = "alive_MEM";
        crew = "LOP_AM_OPF_Infantry_Rifleman";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_aliveMEM_Dshkm_01 : LOP_AM_OPF_Static_DSHKM_OCimport_02 {
        author = "Ryan Parsons";
        scope = 2;
        scopeCurator = 2;
        displayName = "Dshkm";
        side = 0;
        faction = "alive_MEM";
        crew = "LOP_AM_OPF_Infantry_Rifleman";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};